[2023-08-15 20:05:36,639] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-08-07T00:00:00+00:00 [queued]>
[2023-08-15 20:05:36,645] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-08-07T00:00:00+00:00 [queued]>
[2023-08-15 20:05:36,645] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:05:36,645] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-08-15 20:05:36,645] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-15 20:05:36,738] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-08-07 00:00:00+00:00
[2023-08-15 20:05:36,740] {standard_task_runner.py:52} INFO - Started process 45738 to run task
[2023-08-15 20:05:36,745] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-08-07T00:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/dados_climatics.py', '--cfg-path', '/tmp/tmp91bhd4zg', '--error-file', '/tmp/tmpo2grscjw']
[2023-08-15 20:05:36,746] {standard_task_runner.py:80} INFO - Job 75: Subtask cria_pasta
[2023-08-15 20:05:36,852] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-08-07T00:00:00+00:00 [running]> on host ubuntu.internal.cloudapp.net
[2023-08-15 20:05:36,951] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/guilherme/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/guilherme/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/guilherme/airflow/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/guilherme/airflow/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/guilherme/airflow/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/guilherme/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/guilherme/airflow/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/guilherme/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/guilherme/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/guilherme/airflow/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2023-08-15 20:05:36,956] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230807T000000, start_date=20230815T200536, end_date=20230815T200536
[2023-08-15 20:05:37,028] {standard_task_runner.py:92} ERROR - Failed to execute job 75 for task cria_pasta (unexpected end of template, expected ','.; 45738)
[2023-08-15 20:05:37,038] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-08-15 20:05:37,118] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
